# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16c178d09a877a9fedd79a2e46a81d3ed1453d6c329ffa22bda7a8e95cddaf8e041c5f347b4459a0a99df4e3ca7dfa3e48f6fec5d85d5d0c80df568175921659

test:
  secret_key_base: 800074590c97781502d6dfbee6c612978a92826bc48007da4e26e056f356639c9b3e9e55a995fc507c03fc4e833a4e5627738c1c2909997788580c2151ae261e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 16c178d09a877a9fedd79a2e46a81d3ed1453d6c329ffa22bda7aaweaf5cddaf8e041c5f347b4459a0a99df4e3ca7dfa3e48f6fecad85d5d0fg0465568185927656
